name: 7solutions-challenge
services:
  mongo_user:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: ${JWT_TTL}
    depends_on:
      mongo_user:
        condition: service_healthy

volumes:
  mongo_data:
